### ISSUE TITLE
Not enough Porn

### ISSUE THREAD

**Issue by EthanNichols** [rmarks6767/ggj2020#1]
As title reads

**Comment by EthanNichols** [comment]
Please delete this. Didn't realize that posting issues on other repos were visible contributions.

**Comment by crigney3** [comment]
Nice

**Comment by EthanNichols** [comment]
Delete. Not close

**Comment by EthanNichols** [comment]
@rmarks6767 Delete Plz

**Comment by aidan-brown** [comment]
how do you delete
